apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-launchdarkly
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: deployment.yaml
    repoURL: https://github.com/arunprasath42/Go-Launchdarkly.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
