apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-launchdarkly
  labels:
    app: go-launchdarkly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-launchdarkly
  template:
    metadata:
      labels:
        app: go-launchdarkly
    spec:
      containers:
      - name: go-launchdarkly
        image: 9994810592/go-launchdarkly:1.0.0
        ports:
        - containerPort: 80
