apiVersion: v1
kind: Service
metadata:
  name: go-launchdarkly
  labels:
    app: go-launchdarkly
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: go-launchdarkly
  type: LoadBalancer
